### ISSUE TITLE
Remote repository deleted

### ISSUE THREAD

**Issue by AnthonyEbert** [nachoparker/git-forget-blob#2]
Using `git forget-blob` leads to this error when I try to push the changes. 

```
fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>

```

**Comment by nachoparker** [comment]
hi,

As you can see [here](https://ownyourbits.com/2017/01/18/completely-remove-a-file-from-a-git-repository-with-git-forget-blob/), this removes all references, including remotes.

You will have to re-add your remote with `git remote add` and then force push proceed with caution!
